import { prisma } from "../src/lib/prisma";

async function main() {
  console.log("🔧 Seeding ElectroBase database...");

  // Clear existing data
  await prisma.pinConfiguration.deleteMany();
  await prisma.specification.deleteMany();
  await prisma.component.deleteMany();
  await prisma.category.deleteMany();
  await prisma.footprint.deleteMany();

  // ── Categories ──
  const categories = await Promise.all([
    prisma.category.create({ data: { name: "IC", slug: "ic", description: "Integrated Circuits including op-amps, timers, logic gates, and more", icon: "Cpu" } }),
    prisma.category.create({ data: { name: "Resistor", slug: "resistor", description: "Fixed and variable resistors for current limiting and voltage division", icon: "Minus" } }),
    prisma.category.create({ data: { name: "Capacitor", slug: "capacitor", description: "Ceramic, electrolytic, and film capacitors for energy storage and filtering", icon: "Battery" } }),
    prisma.category.create({ data: { name: "Diode", slug: "diode", description: "Rectifier, Zener, Schottky, and LED diodes", icon: "Zap" } }),
    prisma.category.create({ data: { name: "Transistor", slug: "transistor", description: "BJT, MOSFET, and JFET transistors for switching and amplification", icon: "GitBranch" } }),
    prisma.category.create({ data: { name: "Sensor", slug: "sensor", description: "Temperature, humidity, proximity, and other environmental sensors", icon: "Thermometer" } }),
    prisma.category.create({ data: { name: "Microcontroller", slug: "microcontroller", description: "Programmable microcontrollers for embedded systems", icon: "Chip" } }),
    prisma.category.create({ data: { name: "Connector", slug: "connector", description: "Headers, sockets, and various connectors for PCB and wire connections", icon: "Plug" } }),
    prisma.category.create({ data: { name: "Relay", slug: "relay", description: "Electromechanical and solid-state relays for switching high-power loads", icon: "ToggleRight" } }),
    prisma.category.create({ data: { name: "Crystal Oscillator", slug: "crystal-oscillator", description: "Quartz crystals and oscillators for clock generation", icon: "Radio" } }),
  ]);

  console.log(`✅ Created ${categories.length} categories`);

  // ── Footprints ──
  const footprints = await Promise.all([
    prisma.footprint.create({ data: { name: "DIP", description: "Dual In-line Package - through-hole IC package with two parallel rows of pins", dimensions: "Width: 7.62mm-15.24mm, Pin pitch: 2.54mm", recommendedLayout: "Standard through-hole pads with 2.54mm pitch. Drill diameter: 0.8-1.0mm. Pad size: 1.6mm diameter." } }),
    prisma.footprint.create({ data: { name: "SOIC", description: "Small Outline Integrated Circuit - surface mount IC package, smaller than DIP", dimensions: "Width: 3.9mm (narrow) or 7.5mm (wide), Pin pitch: 1.27mm", recommendedLayout: "SMD pads with 1.27mm pitch. Pad size: 0.6mm x 1.5mm. Solder paste stencil opening: 80% of pad." } }),
    prisma.footprint.create({ data: { name: "TSSOP", description: "Thin Shrink Small Outline Package - thinner version of SSOP", dimensions: "Width: 4.4mm, Pin pitch: 0.65mm, Height: 1.0mm", recommendedLayout: "SMD pads with 0.65mm pitch. Pad size: 0.4mm x 1.2mm. Requires solder paste stencil." } }),
    prisma.footprint.create({ data: { name: "QFN", description: "Quad Flat No-lead Package - compact SMD package with exposed thermal pad", dimensions: "Various: 3x3mm to 7x7mm, Pin pitch: 0.5mm-0.65mm", recommendedLayout: "SMD pads around perimeter with 0.5mm pitch. Central thermal pad requires vias for heat dissipation." } }),
    prisma.footprint.create({ data: { name: "BGA", description: "Ball Grid Array - high pin-count package with solder balls underneath", dimensions: "Various sizes, Ball pitch: 0.4mm-1.27mm", recommendedLayout: "Requires multi-layer PCB with via-in-pad or dog-bone routing. Professional assembly recommended." } }),
    prisma.footprint.create({ data: { name: "SOT-23", description: "Small Outline Transistor package with 3-6 pins", dimensions: "2.9mm x 1.3mm x 1.1mm, Pin pitch: 0.95mm", recommendedLayout: "SMD pads with 0.95mm pitch. Pad size: 0.6mm x 0.7mm. Suitable for hand soldering." } }),
    prisma.footprint.create({ data: { name: "TO-220", description: "Through-hole power package with heatsink tab", dimensions: "10.16mm x 15.24mm, Lead pitch: 2.54mm", recommendedLayout: "Through-hole pads with 2.54mm pitch. Drill: 1.0mm. Add mounting hole for heatsink. Keep away from sensitive traces." } }),
    prisma.footprint.create({ data: { name: "TO-92", description: "Small through-hole transistor package with 3 leads", dimensions: "4.19mm x 3.81mm, Lead pitch: 1.27mm", recommendedLayout: "Through-hole pads with 1.27mm pitch. Drill: 0.7mm. Flat side indicates pin 1 orientation." } }),
    prisma.footprint.create({ data: { name: "0805", description: "Imperial 0805 SMD passive component size (metric 2012)", dimensions: "2.0mm x 1.25mm, Height: 0.5-1.0mm", recommendedLayout: "SMD pads: 1.0mm x 1.3mm with 0.5mm gap. Suitable for hand soldering. Most common hobbyist SMD size." } }),
    prisma.footprint.create({ data: { name: "0603", description: "Imperial 0603 SMD passive component size (metric 1608)", dimensions: "1.6mm x 0.8mm, Height: 0.45-0.8mm", recommendedLayout: "SMD pads: 0.8mm x 0.95mm with 0.5mm gap. Requires steady hand or reflow soldering." } }),
    prisma.footprint.create({ data: { name: "0402", description: "Imperial 0402 SMD passive component size (metric 1005)", dimensions: "1.0mm x 0.5mm, Height: 0.35mm", recommendedLayout: "SMD pads: 0.5mm x 0.6mm with 0.3mm gap. Reflow soldering required. Not recommended for hand assembly." } }),
  ]);

  console.log(`✅ Created ${footprints.length} footprints`);

  // ── Components ──
  const components = [
    {
      name: "NE555",
      category: "IC",
      manufacturer: "Texas Instruments",
      description: "The NE555 is a highly stable timer IC capable of producing accurate time delays or oscillation. It can operate in monostable, astable, and bistable modes, making it one of the most versatile and widely used ICs in electronics.",
      datasheetUrl: "https://www.ti.com/lit/ds/symlink/ne555.pdf",
      imageUrl: "/components/ne555.svg",
      footprint: "DIP",
      packageType: "DIP-8",
      pinCount: 8,
      tags: "timer,oscillator,555,pulse",
      pins: [
        { pinNumber: 1, pinName: "GND", description: "Ground reference (0V)" },
        { pinNumber: 2, pinName: "TRIG", description: "Trigger input - starts timing when voltage drops below 1/3 VCC" },
        { pinNumber: 3, pinName: "OUT", description: "Output - goes high during timing period" },
        { pinNumber: 4, pinName: "RESET", description: "Active-low reset input" },
        { pinNumber: 5, pinName: "CTRL", description: "Control voltage - modifies threshold levels" },
        { pinNumber: 6, pinName: "THR", description: "Threshold input - ends timing when voltage rises above 2/3 VCC" },
        { pinNumber: 7, pinName: "DIS", description: "Discharge - open collector output for timing capacitor" },
        { pinNumber: 8, pinName: "VCC", description: "Supply voltage (4.5V to 16V)" },
      ],
      specs: [
        { parameter: "Supply Voltage", value: "4.5 - 16", unit: "V" },
        { parameter: "Supply Current", value: "3 - 6", unit: "mA" },
        { parameter: "Output Current", value: "200", unit: "mA" },
        { parameter: "Timing Range", value: "μs to hours", unit: "" },
        { parameter: "Operating Temperature", value: "0 to 70", unit: "°C" },
      ],
    },
    {
      name: "LM358",
      category: "IC",
      manufacturer: "Texas Instruments",
      description: "The LM358 is a dual operational amplifier with low power consumption. It features two independent, high-gain frequency-compensated op-amps designed for single-supply and split-supply operation.",
      datasheetUrl: "https://www.ti.com/lit/ds/symlink/lm358.pdf",
      imageUrl: "/components/lm358.svg",
      footprint: "DIP",
      packageType: "DIP-8",
      pinCount: 8,
      tags: "op-amp,amplifier,dual,analog",
      pins: [
        { pinNumber: 1, pinName: "OUT1", description: "Output of amplifier 1" },
        { pinNumber: 2, pinName: "IN1-", description: "Inverting input of amplifier 1" },
        { pinNumber: 3, pinName: "IN1+", description: "Non-inverting input of amplifier 1" },
        { pinNumber: 4, pinName: "GND", description: "Ground / V-" },
        { pinNumber: 5, pinName: "IN2+", description: "Non-inverting input of amplifier 2" },
        { pinNumber: 6, pinName: "IN2-", description: "Inverting input of amplifier 2" },
        { pinNumber: 7, pinName: "OUT2", description: "Output of amplifier 2" },
        { pinNumber: 8, pinName: "VCC", description: "Supply voltage" },
      ],
      specs: [
        { parameter: "Supply Voltage", value: "3 - 32", unit: "V" },
        { parameter: "Input Offset Voltage", value: "2", unit: "mV" },
        { parameter: "Gain Bandwidth", value: "1.1", unit: "MHz" },
        { parameter: "Slew Rate", value: "0.6", unit: "V/μs" },
        { parameter: "Supply Current", value: "0.7", unit: "mA" },
      ],
    },
    {
      name: "LM741",
      category: "IC",
      manufacturer: "Texas Instruments",
      description: "The LM741 is a general-purpose single operational amplifier. It is one of the most popular op-amps ever manufactured and is suitable for a wide range of analog circuit applications including amplifiers, filters, and oscillators.",
      datasheetUrl: "https://www.ti.com/lit/ds/symlink/lm741.pdf",
      imageUrl: "/components/lm741.svg",
      footprint: "DIP",
      packageType: "DIP-8",
      pinCount: 8,
      tags: "op-amp,amplifier,single,analog",
      pins: [
        { pinNumber: 1, pinName: "OFFSET N1", description: "Offset null 1" },
        { pinNumber: 2, pinName: "IN-", description: "Inverting input" },
        { pinNumber: 3, pinName: "IN+", description: "Non-inverting input" },
        { pinNumber: 4, pinName: "V-", description: "Negative supply voltage" },
        { pinNumber: 5, pinName: "OFFSET N2", description: "Offset null 2" },
        { pinNumber: 6, pinName: "OUT", description: "Output" },
        { pinNumber: 7, pinName: "V+", description: "Positive supply voltage" },
        { pinNumber: 8, pinName: "NC", description: "No connection" },
      ],
      specs: [
        { parameter: "Supply Voltage", value: "±5 to ±22", unit: "V" },
        { parameter: "Input Offset Voltage", value: "1", unit: "mV" },
        { parameter: "Gain Bandwidth", value: "1.5", unit: "MHz" },
        { parameter: "Slew Rate", value: "0.5", unit: "V/μs" },
        { parameter: "Open Loop Gain", value: "200000", unit: "V/V" },
      ],
    },
    {
      name: "ATmega328P",
      category: "Microcontroller",
      manufacturer: "Microchip",
      description: "The ATmega328P is a high-performance, low-power 8-bit AVR RISC-based microcontroller. It is the heart of the Arduino Uno and features 32KB flash, 2KB SRAM, and 1KB EEPROM with up to 20 MIPS throughput at 20MHz.",
      datasheetUrl: "https://ww1.microchip.com/downloads/en/DeviceDoc/ATmega328P-DS40001984A.pdf",
      imageUrl: "/components/atmega328p.svg",
      footprint: "DIP",
      packageType: "DIP-28",
      pinCount: 28,
      tags: "microcontroller,AVR,Arduino,8-bit,embedded",
      pins: [
        { pinNumber: 1, pinName: "PC6/RESET", description: "Reset input (active low) / Port C bit 6" },
        { pinNumber: 2, pinName: "PD0/RXD", description: "Port D bit 0 / USART receive" },
        { pinNumber: 3, pinName: "PD1/TXD", description: "Port D bit 1 / USART transmit" },
        { pinNumber: 4, pinName: "PD2/INT0", description: "Port D bit 2 / External interrupt 0" },
        { pinNumber: 5, pinName: "PD3/INT1", description: "Port D bit 3 / External interrupt 1" },
        { pinNumber: 6, pinName: "PD4", description: "Port D bit 4" },
        { pinNumber: 7, pinName: "VCC", description: "Supply voltage" },
        { pinNumber: 8, pinName: "GND", description: "Ground" },
        { pinNumber: 9, pinName: "PB6/XTAL1", description: "Port B bit 6 / Crystal oscillator pin 1" },
        { pinNumber: 10, pinName: "PB7/XTAL2", description: "Port B bit 7 / Crystal oscillator pin 2" },
        { pinNumber: 11, pinName: "PD5/OC0B", description: "Port D bit 5 / Timer0 compare B" },
        { pinNumber: 12, pinName: "PD6/OC0A", description: "Port D bit 6 / Timer0 compare A" },
        { pinNumber: 13, pinName: "PD7", description: "Port D bit 7" },
        { pinNumber: 14, pinName: "PB0/ICP1", description: "Port B bit 0 / Input capture 1" },
        { pinNumber: 15, pinName: "PB1/OC1A", description: "Port B bit 1 / Timer1 compare A" },
        { pinNumber: 16, pinName: "PB2/OC1B", description: "Port B bit 2 / Timer1 compare B" },
        { pinNumber: 17, pinName: "PB3/MOSI", description: "Port B bit 3 / SPI MOSI" },
        { pinNumber: 18, pinName: "PB4/MISO", description: "Port B bit 4 / SPI MISO" },
        { pinNumber: 19, pinName: "PB5/SCK", description: "Port B bit 5 / SPI clock / LED on Arduino" },
        { pinNumber: 20, pinName: "AVCC", description: "Analog supply voltage" },
        { pinNumber: 21, pinName: "AREF", description: "Analog reference voltage" },
        { pinNumber: 22, pinName: "GND", description: "Ground" },
        { pinNumber: 23, pinName: "PC0/ADC0", description: "Port C bit 0 / ADC channel 0" },
        { pinNumber: 24, pinName: "PC1/ADC1", description: "Port C bit 1 / ADC channel 1" },
        { pinNumber: 25, pinName: "PC2/ADC2", description: "Port C bit 2 / ADC channel 2" },
        { pinNumber: 26, pinName: "PC3/ADC3", description: "Port C bit 3 / ADC channel 3" },
        { pinNumber: 27, pinName: "PC4/SDA", description: "Port C bit 4 / I2C data" },
        { pinNumber: 28, pinName: "PC5/SCL", description: "Port C bit 5 / I2C clock" },
      ],
      specs: [
        { parameter: "Flash Memory", value: "32", unit: "KB" },
        { parameter: "SRAM", value: "2", unit: "KB" },
        { parameter: "EEPROM", value: "1", unit: "KB" },
        { parameter: "Clock Speed", value: "20", unit: "MHz" },
        { parameter: "Operating Voltage", value: "1.8 - 5.5", unit: "V" },
        { parameter: "Digital I/O Pins", value: "23", unit: "" },
        { parameter: "ADC Channels", value: "6", unit: "" },
        { parameter: "PWM Channels", value: "6", unit: "" },
      ],
    },
    {
      name: "ESP32-WROOM-32",
      category: "Microcontroller",
      manufacturer: "Espressif",
      description: "The ESP32-WROOM-32 is a powerful Wi-Fi and Bluetooth dual-mode module based on the ESP32 chip. It features a dual-core 32-bit processor running at up to 240MHz, 520KB SRAM, and integrated Wi-Fi 802.11 b/g/n and Bluetooth 4.2.",
      datasheetUrl: "https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf",
      imageUrl: "/components/esp32.svg",
      footprint: "QFN",
      packageType: "Module",
      pinCount: 38,
      tags: "WiFi,Bluetooth,IoT,dual-core,ESP32,wireless",
      pins: [
        { pinNumber: 1, pinName: "3V3", description: "3.3V power supply" },
        { pinNumber: 2, pinName: "EN", description: "Chip enable (active high)" },
        { pinNumber: 3, pinName: "GPIO36/SVP", description: "ADC1_CH0 / Sensor VP" },
        { pinNumber: 4, pinName: "GPIO39/SVN", description: "ADC1_CH3 / Sensor VN" },
        { pinNumber: 5, pinName: "GPIO34", description: "ADC1_CH6 (input only)" },
        { pinNumber: 6, pinName: "GPIO35", description: "ADC1_CH7 (input only)" },
        { pinNumber: 7, pinName: "GPIO32", description: "ADC1_CH4 / Touch9" },
        { pinNumber: 8, pinName: "GPIO33", description: "ADC1_CH5 / Touch8" },
        { pinNumber: 9, pinName: "GPIO25/DAC1", description: "ADC2_CH8 / DAC channel 1" },
        { pinNumber: 10, pinName: "GPIO26/DAC2", description: "ADC2_CH9 / DAC channel 2" },
      ],
      specs: [
        { parameter: "CPU", value: "Xtensa Dual-Core 32-bit LX6", unit: "" },
        { parameter: "Clock Speed", value: "240", unit: "MHz" },
        { parameter: "SRAM", value: "520", unit: "KB" },
        { parameter: "Flash", value: "4", unit: "MB" },
        { parameter: "Wi-Fi", value: "802.11 b/g/n", unit: "" },
        { parameter: "Bluetooth", value: "4.2 BR/EDR + BLE", unit: "" },
        { parameter: "Operating Voltage", value: "3.0 - 3.6", unit: "V" },
        { parameter: "GPIO Pins", value: "34", unit: "" },
      ],
    },
    {
      name: "STM32F103C8T6",
      category: "Microcontroller",
      manufacturer: "STMicroelectronics",
      description: "The STM32F103C8T6 (Blue Pill) is a 32-bit ARM Cortex-M3 microcontroller running at 72MHz. It offers 64KB flash memory, 20KB SRAM, USB, CAN, I2C, SPI, USART interfaces, and 12-bit ADC.",
      datasheetUrl: "https://www.st.com/resource/en/datasheet/stm32f103c8.pdf",
      imageUrl: "/components/stm32f103.svg",
      footprint: "QFN",
      packageType: "LQFP-48",
      pinCount: 48,
      tags: "ARM,Cortex-M3,STM32,32-bit,Blue Pill,embedded",
      pins: [
        { pinNumber: 1, pinName: "VBAT", description: "Battery supply for RTC and backup registers" },
        { pinNumber: 2, pinName: "PC13", description: "GPIO / LED on Blue Pill board" },
        { pinNumber: 3, pinName: "PC14/OSC32_IN", description: "32.768 kHz oscillator input" },
        { pinNumber: 4, pinName: "PC15/OSC32_OUT", description: "32.768 kHz oscillator output" },
        { pinNumber: 5, pinName: "OSC_IN", description: "HSE oscillator input (8MHz)" },
        { pinNumber: 6, pinName: "OSC_OUT", description: "HSE oscillator output" },
        { pinNumber: 7, pinName: "NRST", description: "Reset (active low)" },
        { pinNumber: 8, pinName: "VSSA", description: "Analog ground" },
      ],
      specs: [
        { parameter: "CPU Core", value: "ARM Cortex-M3", unit: "" },
        { parameter: "Clock Speed", value: "72", unit: "MHz" },
        { parameter: "Flash Memory", value: "64", unit: "KB" },
        { parameter: "SRAM", value: "20", unit: "KB" },
        { parameter: "Operating Voltage", value: "2.0 - 3.6", unit: "V" },
        { parameter: "ADC Resolution", value: "12", unit: "bit" },
        { parameter: "USB", value: "Full-Speed", unit: "" },
      ],
    },
    {
      name: "74HC595",
      category: "IC",
      manufacturer: "Texas Instruments",
      description: "The 74HC595 is an 8-bit serial-in, parallel-out shift register with output latch and three-state outputs. It is commonly used to expand the number of output pins on a microcontroller.",
      datasheetUrl: "https://www.ti.com/lit/ds/symlink/sn74hc595.pdf",
      imageUrl: "/components/74hc595.svg",
      footprint: "DIP",
      packageType: "DIP-16",
      pinCount: 16,
      tags: "shift register,serial,parallel,logic,digital",
      pins: [
        { pinNumber: 1, pinName: "QB", description: "Parallel output B" },
        { pinNumber: 2, pinName: "QC", description: "Parallel output C" },
        { pinNumber: 3, pinName: "QD", description: "Parallel output D" },
        { pinNumber: 4, pinName: "QE", description: "Parallel output E" },
        { pinNumber: 5, pinName: "QF", description: "Parallel output F" },
        { pinNumber: 6, pinName: "QG", description: "Parallel output G" },
        { pinNumber: 7, pinName: "QH", description: "Parallel output H" },
        { pinNumber: 8, pinName: "GND", description: "Ground" },
        { pinNumber: 9, pinName: "QH'", description: "Serial output for daisy-chaining" },
        { pinNumber: 10, pinName: "SRCLR", description: "Shift register clear (active low)" },
        { pinNumber: 11, pinName: "SRCLK", description: "Shift register clock" },
        { pinNumber: 12, pinName: "RCLK", description: "Storage register clock (latch)" },
        { pinNumber: 13, pinName: "OE", description: "Output enable (active low)" },
        { pinNumber: 14, pinName: "SER", description: "Serial data input" },
        { pinNumber: 15, pinName: "QA", description: "Parallel output A" },
        { pinNumber: 16, pinName: "VCC", description: "Supply voltage" },
      ],
      specs: [
        { parameter: "Supply Voltage", value: "2 - 6", unit: "V" },
        { parameter: "Max Clock Frequency", value: "25", unit: "MHz" },
        { parameter: "Output Current", value: "35", unit: "mA" },
        { parameter: "Operating Temperature", value: "-40 to 125", unit: "°C" },
      ],
    },
    {
      name: "74LS08",
      category: "IC",
      manufacturer: "Texas Instruments",
      description: "The 74LS08 contains four independent 2-input AND gates in a single DIP-14 package. It is part of the 7400 series TTL logic family and is widely used in digital circuit design.",
      datasheetUrl: "https://www.ti.com/lit/ds/symlink/sn74ls08.pdf",
      imageUrl: "/components/74ls08.svg",
      footprint: "DIP",
      packageType: "DIP-14",
      pinCount: 14,
      tags: "logic gate,AND,TTL,digital,7400 series",
      pins: [
        { pinNumber: 1, pinName: "1A", description: "Gate 1 input A" },
        { pinNumber: 2, pinName: "1B", description: "Gate 1 input B" },
        { pinNumber: 3, pinName: "1Y", description: "Gate 1 output" },
        { pinNumber: 4, pinName: "2A", description: "Gate 2 input A" },
        { pinNumber: 5, pinName: "2B", description: "Gate 2 input B" },
        { pinNumber: 6, pinName: "2Y", description: "Gate 2 output" },
        { pinNumber: 7, pinName: "GND", description: "Ground" },
        { pinNumber: 8, pinName: "3Y", description: "Gate 3 output" },
        { pinNumber: 9, pinName: "3A", description: "Gate 3 input A" },
        { pinNumber: 10, pinName: "3B", description: "Gate 3 input B" },
        { pinNumber: 11, pinName: "4Y", description: "Gate 4 output" },
        { pinNumber: 12, pinName: "4A", description: "Gate 4 input A" },
        { pinNumber: 13, pinName: "4B", description: "Gate 4 input B" },
        { pinNumber: 14, pinName: "VCC", description: "Supply voltage (+5V)" },
      ],
      specs: [
        { parameter: "Supply Voltage", value: "4.75 - 5.25", unit: "V" },
        { parameter: "Input High Voltage", value: "2.0", unit: "V" },
        { parameter: "Input Low Voltage", value: "0.8", unit: "V" },
        { parameter: "Propagation Delay", value: "15", unit: "ns" },
      ],
    },
    {
      name: "7805",
      category: "IC",
      manufacturer: "STMicroelectronics",
      description: "The 7805 is a fixed positive voltage regulator that provides a stable +5V output. It features thermal overload protection, short-circuit protection, and output transistor safe-area compensation.",
      datasheetUrl: "https://www.st.com/resource/en/datasheet/l78.pdf",
      imageUrl: "/components/7805.svg",
      footprint: "TO-220",
      packageType: "TO-220",
      pinCount: 3,
      tags: "voltage regulator,5V,linear,power,78xx",
      pins: [
        { pinNumber: 1, pinName: "IN", description: "Input voltage (7V to 35V)" },
        { pinNumber: 2, pinName: "GND", description: "Ground reference" },
        { pinNumber: 3, pinName: "OUT", description: "Regulated output (+5V)" },
      ],
      specs: [
        { parameter: "Output Voltage", value: "5", unit: "V" },
        { parameter: "Input Voltage Range", value: "7 - 35", unit: "V" },
        { parameter: "Output Current", value: "1.5", unit: "A" },
        { parameter: "Dropout Voltage", value: "2", unit: "V" },
        { parameter: "Load Regulation", value: "10", unit: "mV" },
      ],
    },
    {
      name: "AMS1117-3.3",
      category: "IC",
      manufacturer: "Advanced Monolithic Systems",
      description: "The AMS1117-3.3 is a low-dropout (LDO) voltage regulator providing a fixed 3.3V output at up to 1A. It is widely used in 3.3V power supply designs for microcontrollers, Wi-Fi modules, and other digital circuits.",
      datasheetUrl: "http://www.advanced-monolithic.com/pdf/ds1117.pdf",
      imageUrl: "/components/ams1117.svg",
      footprint: "SOT-23",
      packageType: "SOT-223",
      pinCount: 3,
      tags: "LDO,voltage regulator,3.3V,power,linear",
      pins: [
        { pinNumber: 1, pinName: "GND/ADJ", description: "Ground / Adjust pin" },
        { pinNumber: 2, pinName: "VOUT", description: "Regulated output (3.3V)" },
        { pinNumber: 3, pinName: "VIN", description: "Input voltage" },
      ],
      specs: [
        { parameter: "Output Voltage", value: "3.3", unit: "V" },
        { parameter: "Input Voltage Range", value: "4.5 - 12", unit: "V" },
        { parameter: "Dropout Voltage", value: "1.0", unit: "V" },
        { parameter: "Output Current", value: "1", unit: "A" },
        { parameter: "Quiescent Current", value: "5", unit: "mA" },
      ],
    },
    {
      name: "BC547",
      category: "Transistor",
      manufacturer: "ON Semiconductor",
      description: "The BC547 is a general-purpose NPN bipolar junction transistor used for switching and amplification applications. It features low noise and high current gain, making it ideal for audio and general-purpose circuits.",
      datasheetUrl: "https://www.onsemi.com/pdf/datasheet/bc546-d.pdf",
      imageUrl: "/components/bc547.svg",
      footprint: "TO-92",
      packageType: "TO-92",
      pinCount: 3,
      tags: "NPN,BJT,transistor,switching,amplifier",
      pins: [
        { pinNumber: 1, pinName: "C", description: "Collector" },
        { pinNumber: 2, pinName: "B", description: "Base" },
        { pinNumber: 3, pinName: "E", description: "Emitter" },
      ],
      specs: [
        { parameter: "Type", value: "NPN", unit: "" },
        { parameter: "VCEO", value: "45", unit: "V" },
        { parameter: "IC Max", value: "100", unit: "mA" },
        { parameter: "hFE", value: "110 - 800", unit: "" },
        { parameter: "fT", value: "300", unit: "MHz" },
        { parameter: "Power Dissipation", value: "625", unit: "mW" },
      ],
    },
    {
      name: "2N2222",
      category: "Transistor",
      manufacturer: "ON Semiconductor",
      description: "The 2N2222 is a common NPN bipolar junction transistor used for general-purpose switching and amplification. It can handle moderate currents and voltages and is one of the most popular transistors.",
      datasheetUrl: "https://www.onsemi.com/pdf/datasheet/p2n2222a-d.pdf",
      imageUrl: "/components/2n2222.svg",
      footprint: "TO-92",
      packageType: "TO-92",
      pinCount: 3,
      tags: "NPN,BJT,transistor,switching,general purpose",
      pins: [
        { pinNumber: 1, pinName: "E", description: "Emitter" },
        { pinNumber: 2, pinName: "B", description: "Base" },
        { pinNumber: 3, pinName: "C", description: "Collector" },
      ],
      specs: [
        { parameter: "Type", value: "NPN", unit: "" },
        { parameter: "VCEO", value: "40", unit: "V" },
        { parameter: "IC Max", value: "800", unit: "mA" },
        { parameter: "hFE", value: "100 - 300", unit: "" },
        { parameter: "fT", value: "300", unit: "MHz" },
        { parameter: "Power Dissipation", value: "625", unit: "mW" },
      ],
    },
    {
      name: "IRFZ44N",
      category: "Transistor",
      manufacturer: "International Rectifier",
      description: "The IRFZ44N is an N-channel power MOSFET designed for high-current switching applications. With very low on-resistance and high current capability, it is ideal for motor drivers, power supplies, and automotive circuits.",
      datasheetUrl: "https://www.infineon.com/dgdl/irfz44n.pdf",
      imageUrl: "/components/irfz44n.svg",
      footprint: "TO-220",
      packageType: "TO-220AB",
      pinCount: 3,
      tags: "MOSFET,N-channel,power,switching,motor driver",
      pins: [
        { pinNumber: 1, pinName: "G", description: "Gate" },
        { pinNumber: 2, pinName: "D", description: "Drain" },
        { pinNumber: 3, pinName: "S", description: "Source" },
      ],
      specs: [
        { parameter: "Type", value: "N-Channel MOSFET", unit: "" },
        { parameter: "VDS", value: "55", unit: "V" },
        { parameter: "ID", value: "49", unit: "A" },
        { parameter: "RDS(on)", value: "17.5", unit: "mΩ" },
        { parameter: "VGS(th)", value: "2 - 4", unit: "V" },
        { parameter: "Power Dissipation", value: "94", unit: "W" },
      ],
    },
    {
      name: "1N4007",
      category: "Diode",
      manufacturer: "Vishay",
      description: "The 1N4007 is a general-purpose silicon rectifier diode rated for 1000V reverse voltage and 1A forward current. It is used extensively in power supply rectification and protection circuits.",
      datasheetUrl: "https://www.vishay.com/docs/88503/1n4001.pdf",
      imageUrl: "/components/1n4007.svg",
      footprint: "DIP",
      packageType: "DO-41",
      pinCount: 2,
      tags: "rectifier,diode,1N4007,power,protection",
      pins: [
        { pinNumber: 1, pinName: "A", description: "Anode" },
        { pinNumber: 2, pinName: "K", description: "Cathode (marked with band)" },
      ],
      specs: [
        { parameter: "Max Reverse Voltage", value: "1000", unit: "V" },
        { parameter: "Forward Current", value: "1", unit: "A" },
        { parameter: "Forward Voltage Drop", value: "1.1", unit: "V" },
        { parameter: "Reverse Recovery Time", value: "30", unit: "μs" },
      ],
    },
    {
      name: "1N4148",
      category: "Diode",
      manufacturer: "NXP Semiconductors",
      description: "The 1N4148 is a high-speed switching diode commonly used in signal processing, clamping, and protection circuits. Its fast switching speed makes it suitable for high-frequency applications.",
      datasheetUrl: "https://www.nxp.com/docs/en/data-sheet/1N4148_1N4448.pdf",
      imageUrl: "/components/1n4148.svg",
      footprint: "DIP",
      packageType: "DO-35",
      pinCount: 2,
      tags: "switching diode,signal,fast,high-speed,protection",
      pins: [
        { pinNumber: 1, pinName: "A", description: "Anode" },
        { pinNumber: 2, pinName: "K", description: "Cathode" },
      ],
      specs: [
        { parameter: "Max Reverse Voltage", value: "100", unit: "V" },
        { parameter: "Forward Current", value: "200", unit: "mA" },
        { parameter: "Forward Voltage", value: "0.72", unit: "V" },
        { parameter: "Reverse Recovery Time", value: "4", unit: "ns" },
      ],
    },
    {
      name: "5mm Red LED",
      category: "Diode",
      manufacturer: "Kingbright",
      description: "A standard 5mm red LED (Light Emitting Diode) with diffused lens. Commonly used as an indicator light in electronics projects, panels, and displays.",
      datasheetUrl: "https://www.kingbrightusa.com/images/catalog/SPEC/WP7113ID.pdf",
      imageUrl: "/components/led-red.svg",
      footprint: "DIP",
      packageType: "5mm Radial",
      pinCount: 2,
      tags: "LED,red,indicator,light,display",
      pins: [
        { pinNumber: 1, pinName: "A", description: "Anode (longer lead)" },
        { pinNumber: 2, pinName: "K", description: "Cathode (shorter lead / flat side)" },
      ],
      specs: [
        { parameter: "Forward Voltage", value: "1.8 - 2.2", unit: "V" },
        { parameter: "Forward Current", value: "20", unit: "mA" },
        { parameter: "Wavelength", value: "620 - 635", unit: "nm" },
        { parameter: "Luminous Intensity", value: "200", unit: "mcd" },
        { parameter: "Viewing Angle", value: "30", unit: "°" },
      ],
    },
    {
      name: "DHT11",
      category: "Sensor",
      manufacturer: "Aosong",
      description: "The DHT11 is a basic, ultra-low-cost digital temperature and humidity sensor. It uses a capacitive humidity sensor and a thermistor to measure the surrounding air, providing a digital signal on the data pin.",
      datasheetUrl: "https://www.mouser.com/datasheet/2/758/DHT11-Technical-Data-Sheet-Translated-Version-1143054.pdf",
      imageUrl: "/components/dht11.svg",
      footprint: "DIP",
      packageType: "4-pin Module",
      pinCount: 4,
      tags: "temperature,humidity,sensor,digital,weather",
      pins: [
        { pinNumber: 1, pinName: "VCC", description: "Power supply (3.3V - 5V)" },
        { pinNumber: 2, pinName: "DATA", description: "Digital data output" },
        { pinNumber: 3, pinName: "NC", description: "No connection" },
        { pinNumber: 4, pinName: "GND", description: "Ground" },
      ],
      specs: [
        { parameter: "Operating Voltage", value: "3.3 - 5.5", unit: "V" },
        { parameter: "Temperature Range", value: "0 - 50", unit: "°C" },
        { parameter: "Temperature Accuracy", value: "±2", unit: "°C" },
        { parameter: "Humidity Range", value: "20 - 80", unit: "% RH" },
        { parameter: "Humidity Accuracy", value: "±5", unit: "% RH" },
        { parameter: "Sampling Period", value: "1", unit: "s" },
      ],
    },
    {
      name: "DHT22",
      category: "Sensor",
      manufacturer: "Aosong",
      description: "The DHT22 (AM2302) is a more accurate version of the DHT11, offering wider range and better precision for temperature and humidity measurement. Suitable for weather stations and HVAC applications.",
      datasheetUrl: "https://www.sparkfun.com/datasheets/Sensors/Temperature/DHT22.pdf",
      imageUrl: "/components/dht22.svg",
      footprint: "DIP",
      packageType: "4-pin Module",
      pinCount: 4,
      tags: "temperature,humidity,sensor,digital,precision",
      pins: [
        { pinNumber: 1, pinName: "VCC", description: "Power supply (3.3V - 6V)" },
        { pinNumber: 2, pinName: "DATA", description: "Digital data output" },
        { pinNumber: 3, pinName: "NC", description: "No connection" },
        { pinNumber: 4, pinName: "GND", description: "Ground" },
      ],
      specs: [
        { parameter: "Operating Voltage", value: "3.3 - 6", unit: "V" },
        { parameter: "Temperature Range", value: "-40 - 80", unit: "°C" },
        { parameter: "Temperature Accuracy", value: "±0.5", unit: "°C" },
        { parameter: "Humidity Range", value: "0 - 100", unit: "% RH" },
        { parameter: "Humidity Accuracy", value: "±2", unit: "% RH" },
        { parameter: "Sampling Period", value: "2", unit: "s" },
      ],
    },
    {
      name: "HC-SR04",
      category: "Sensor",
      manufacturer: "Generic",
      description: "The HC-SR04 is an ultrasonic distance sensor that provides 2cm to 400cm non-contact measurement with accuracy up to 3mm. It uses sonar to determine distance to objects.",
      datasheetUrl: "https://cdn.sparkfun.com/datasheets/Sensors/Proximity/HCSR04.pdf",
      imageUrl: "/components/hcsr04.svg",
      footprint: "DIP",
      packageType: "Module",
      pinCount: 4,
      tags: "ultrasonic,distance,sensor,proximity,ranging",
      pins: [
        { pinNumber: 1, pinName: "VCC", description: "Power supply (+5V)" },
        { pinNumber: 2, pinName: "TRIG", description: "Trigger input (10μs pulse)" },
        { pinNumber: 3, pinName: "ECHO", description: "Echo output (pulse width = distance)" },
        { pinNumber: 4, pinName: "GND", description: "Ground" },
      ],
      specs: [
        { parameter: "Operating Voltage", value: "5", unit: "V" },
        { parameter: "Measuring Range", value: "2 - 400", unit: "cm" },
        { parameter: "Measuring Angle", value: "15", unit: "°" },
        { parameter: "Resolution", value: "3", unit: "mm" },
        { parameter: "Trigger Pulse", value: "10", unit: "μs" },
      ],
    },
    {
      name: "MFRC522",
      category: "Sensor",
      manufacturer: "NXP Semiconductors",
      description: "The MFRC522 is a highly integrated RFID reader/writer IC for contactless communication at 13.56 MHz. It supports ISO/IEC 14443 A/MIFARE and is commonly used in access control and IoT projects.",
      datasheetUrl: "https://www.nxp.com/docs/en/data-sheet/MFRC522.pdf",
      imageUrl: "/components/mfrc522.svg",
      footprint: "QFN",
      packageType: "Module",
      pinCount: 8,
      tags: "RFID,NFC,13.56MHz,reader,SPI,contactless",
      pins: [
        { pinNumber: 1, pinName: "SDA/SS", description: "SPI Slave Select / I2C Data" },
        { pinNumber: 2, pinName: "SCK", description: "SPI Clock" },
        { pinNumber: 3, pinName: "MOSI", description: "SPI Master Out Slave In" },
        { pinNumber: 4, pinName: "MISO", description: "SPI Master In Slave Out" },
        { pinNumber: 5, pinName: "IRQ", description: "Interrupt output" },
        { pinNumber: 6, pinName: "GND", description: "Ground" },
        { pinNumber: 7, pinName: "RST", description: "Reset" },
        { pinNumber: 8, pinName: "3.3V", description: "Power supply (3.3V)" },
      ],
      specs: [
        { parameter: "Operating Voltage", value: "2.5 - 3.3", unit: "V" },
        { parameter: "Operating Frequency", value: "13.56", unit: "MHz" },
        { parameter: "Read Range", value: "0 - 60", unit: "mm" },
        { parameter: "Interface", value: "SPI / I2C / UART", unit: "" },
        { parameter: "Data Transfer Rate", value: "10", unit: "Mbit/s" },
      ],
    },
    {
      name: "SSD1306 OLED",
      category: "IC",
      manufacturer: "Solomon Systech",
      description: "The SSD1306 is a single-chip CMOS OLED/PLED driver with controller for 128x64 dot matrix display. It supports I2C and SPI interfaces and is widely used in small OLED display modules.",
      datasheetUrl: "https://cdn-shop.adafruit.com/datasheets/SSD1306.pdf",
      imageUrl: "/components/ssd1306.svg",
      footprint: "DIP",
      packageType: "Module",
      pinCount: 4,
      tags: "OLED,display,I2C,SPI,128x64,screen",
      pins: [
        { pinNumber: 1, pinName: "GND", description: "Ground" },
        { pinNumber: 2, pinName: "VCC", description: "Power supply (3.3V - 5V)" },
        { pinNumber: 3, pinName: "SCL", description: "I2C Clock" },
        { pinNumber: 4, pinName: "SDA", description: "I2C Data" },
      ],
      specs: [
        { parameter: "Display Type", value: "OLED", unit: "" },
        { parameter: "Resolution", value: "128 x 64", unit: "pixels" },
        { parameter: "Display Size", value: "0.96", unit: "inches" },
        { parameter: "Operating Voltage", value: "3.3 - 5", unit: "V" },
        { parameter: "Interface", value: "I2C (0x3C)", unit: "" },
        { parameter: "Viewing Angle", value: "160", unit: "°" },
      ],
    },
    {
      name: "LM7812",
      category: "IC",
      manufacturer: "STMicroelectronics",
      description: "The LM7812 is a fixed +12V positive voltage regulator capable of supplying up to 1.5A of output current. It includes internal thermal overload protection and short-circuit current limiting.",
      datasheetUrl: "https://www.st.com/resource/en/datasheet/l78.pdf",
      imageUrl: "/components/lm7812.svg",
      footprint: "TO-220",
      packageType: "TO-220",
      pinCount: 3,
      tags: "voltage regulator,12V,linear,power,78xx",
      pins: [
        { pinNumber: 1, pinName: "IN", description: "Input voltage (14V to 35V)" },
        { pinNumber: 2, pinName: "GND", description: "Ground reference" },
        { pinNumber: 3, pinName: "OUT", description: "Regulated output (+12V)" },
      ],
      specs: [
        { parameter: "Output Voltage", value: "12", unit: "V" },
        { parameter: "Input Voltage Range", value: "14 - 35", unit: "V" },
        { parameter: "Output Current", value: "1.5", unit: "A" },
        { parameter: "Dropout Voltage", value: "2", unit: "V" },
      ],
    },
    {
      name: "LM317",
      category: "IC",
      manufacturer: "Texas Instruments",
      description: "The LM317 is an adjustable positive voltage regulator capable of supplying 1.5A over an output voltage range of 1.25V to 37V. It requires only two external resistors to set the output voltage.",
      datasheetUrl: "https://www.ti.com/lit/ds/symlink/lm317.pdf",
      imageUrl: "/components/lm317.svg",
      footprint: "TO-220",
      packageType: "TO-220",
      pinCount: 3,
      tags: "voltage regulator,adjustable,linear,power,LDO",
      pins: [
        { pinNumber: 1, pinName: "ADJ", description: "Adjustment pin" },
        { pinNumber: 2, pinName: "VOUT", description: "Output voltage (1.25V to 37V)" },
        { pinNumber: 3, pinName: "VIN", description: "Input voltage" },
      ],
      specs: [
        { parameter: "Output Voltage Range", value: "1.25 - 37", unit: "V" },
        { parameter: "Output Current", value: "1.5", unit: "A" },
        { parameter: "Reference Voltage", value: "1.25", unit: "V" },
        { parameter: "Line Regulation", value: "0.01", unit: "%/V" },
      ],
    },
    {
      name: "TL431",
      category: "IC",
      manufacturer: "Texas Instruments",
      description: "The TL431 is a programmable shunt regulator providing a precise voltage reference from 2.5V to 36V. It is commonly used in power supply feedback circuits and voltage reference applications.",
      datasheetUrl: "https://www.ti.com/lit/ds/symlink/tl431.pdf",
      imageUrl: "/components/tl431.svg",
      footprint: "TO-92",
      packageType: "TO-92",
      pinCount: 3,
      tags: "voltage reference,shunt regulator,power supply,feedback",
      pins: [
        { pinNumber: 1, pinName: "REF", description: "Reference input" },
        { pinNumber: 2, pinName: "A", description: "Anode" },
        { pinNumber: 3, pinName: "K", description: "Cathode" },
      ],
      specs: [
        { parameter: "Reference Voltage", value: "2.495", unit: "V" },
        { parameter: "Voltage Range", value: "2.5 - 36", unit: "V" },
        { parameter: "Cathode Current", value: "1 - 100", unit: "mA" },
        { parameter: "Reference Tolerance", value: "0.4", unit: "%" },
      ],
    },
    {
      name: "LDR (GL5528)",
      category: "Sensor",
      manufacturer: "Generic",
      description: "The GL5528 Light Dependent Resistor (LDR) is a photoresistor whose resistance decreases with increasing light intensity. It is commonly used in light-sensing circuits, automatic lighting, and dark-activated switches.",
      datasheetUrl: "https://components101.com/sites/default/files/component_datasheet/LDR%20Datasheet.pdf",
      imageUrl: "/components/ldr.svg",
      footprint: "DIP",
      packageType: "Radial",
      pinCount: 2,
      tags: "photoresistor,light sensor,LDR,analog,illumination",
      pins: [
        { pinNumber: 1, pinName: "P1", description: "Terminal 1 (no polarity)" },
        { pinNumber: 2, pinName: "P2", description: "Terminal 2 (no polarity)" },
      ],
      specs: [
        { parameter: "Light Resistance", value: "8 - 20", unit: "kΩ" },
        { parameter: "Dark Resistance", value: "1", unit: "MΩ" },
        { parameter: "Peak Wavelength", value: "540", unit: "nm" },
        { parameter: "Power Dissipation", value: "100", unit: "mW" },
      ],
    },
    {
      name: "10kΩ Resistor",
      category: "Resistor",
      manufacturer: "Yageo",
      description: "A standard 10kΩ metal film resistor with 1% tolerance. One of the most commonly used resistor values in electronics, suitable for pull-up/pull-down resistors, voltage dividers, and biasing circuits.",
      datasheetUrl: "https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-MF_51_RoHS_L_1.pdf",
      imageUrl: "/components/resistor-10k.svg",
      footprint: "0805",
      packageType: "0805",
      pinCount: 2,
      tags: "resistor,10k,pull-up,pull-down,passive",
      pins: [
        { pinNumber: 1, pinName: "T1", description: "Terminal 1 (no polarity)" },
        { pinNumber: 2, pinName: "T2", description: "Terminal 2 (no polarity)" },
      ],
      specs: [
        { parameter: "Resistance", value: "10", unit: "kΩ" },
        { parameter: "Tolerance", value: "±1", unit: "%" },
        { parameter: "Power Rating", value: "0.125", unit: "W" },
        { parameter: "Temperature Coefficient", value: "±100", unit: "ppm/°C" },
      ],
    },
    {
      name: "1kΩ Resistor",
      category: "Resistor",
      manufacturer: "Yageo",
      description: "A standard 1kΩ metal film resistor with 1% tolerance. Commonly used for LED current limiting, signal conditioning, and general-purpose circuit design.",
      datasheetUrl: "https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-MF_51_RoHS_L_1.pdf",
      imageUrl: "/components/resistor-1k.svg",
      footprint: "0805",
      packageType: "0805",
      pinCount: 2,
      tags: "resistor,1k,LED,current limiting,passive",
      pins: [
        { pinNumber: 1, pinName: "T1", description: "Terminal 1" },
        { pinNumber: 2, pinName: "T2", description: "Terminal 2" },
      ],
      specs: [
        { parameter: "Resistance", value: "1", unit: "kΩ" },
        { parameter: "Tolerance", value: "±1", unit: "%" },
        { parameter: "Power Rating", value: "0.125", unit: "W" },
      ],
    },
    {
      name: "220Ω Resistor",
      category: "Resistor",
      manufacturer: "Yageo",
      description: "A standard 220Ω metal film resistor with 5% tolerance. The go-to resistor for LED current limiting with 5V supply, providing approximately 15mA of current.",
      datasheetUrl: "https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-MF_51_RoHS_L_1.pdf",
      imageUrl: "/components/resistor-220.svg",
      footprint: "0805",
      packageType: "0805",
      pinCount: 2,
      tags: "resistor,220,LED,current limiting,passive",
      pins: [
        { pinNumber: 1, pinName: "T1", description: "Terminal 1" },
        { pinNumber: 2, pinName: "T2", description: "Terminal 2" },
      ],
      specs: [
        { parameter: "Resistance", value: "220", unit: "Ω" },
        { parameter: "Tolerance", value: "±5", unit: "%" },
        { parameter: "Power Rating", value: "0.125", unit: "W" },
      ],
    },
    {
      name: "4.7kΩ Resistor",
      category: "Resistor",
      manufacturer: "Yageo",
      description: "A 4.7kΩ metal film resistor with 1% tolerance. Commonly used as pull-up resistor for I2C bus lines and other standard applications.",
      datasheetUrl: "https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-MF_51_RoHS_L_1.pdf",
      imageUrl: "/components/resistor-4k7.svg",
      footprint: "0603",
      packageType: "0603",
      pinCount: 2,
      tags: "resistor,4.7k,I2C,pull-up,passive",
      pins: [
        { pinNumber: 1, pinName: "T1", description: "Terminal 1" },
        { pinNumber: 2, pinName: "T2", description: "Terminal 2" },
      ],
      specs: [
        { parameter: "Resistance", value: "4.7", unit: "kΩ" },
        { parameter: "Tolerance", value: "±1", unit: "%" },
        { parameter: "Power Rating", value: "0.1", unit: "W" },
      ],
    },
    {
      name: "100nF Ceramic Capacitor",
      category: "Capacitor",
      manufacturer: "Murata",
      description: "A 100nF (0.1μF) multi-layer ceramic capacitor (MLCC) with X7R dielectric. The standard decoupling capacitor used on every IC power pin for filtering high-frequency noise.",
      datasheetUrl: "https://www.murata.com/en-us/products/productdata/8796747038750/ENAB.pdf",
      imageUrl: "/components/cap-100nf.svg",
      footprint: "0805",
      packageType: "0805",
      pinCount: 2,
      tags: "capacitor,100nF,decoupling,ceramic,bypass,MLCC",
      pins: [
        { pinNumber: 1, pinName: "T1", description: "Terminal 1 (no polarity)" },
        { pinNumber: 2, pinName: "T2", description: "Terminal 2 (no polarity)" },
      ],
      specs: [
        { parameter: "Capacitance", value: "100", unit: "nF" },
        { parameter: "Voltage Rating", value: "50", unit: "V" },
        { parameter: "Dielectric", value: "X7R", unit: "" },
        { parameter: "Tolerance", value: "±10", unit: "%" },
        { parameter: "Temperature Range", value: "-55 to 125", unit: "°C" },
      ],
    },
    {
      name: "10μF Electrolytic Capacitor",
      category: "Capacitor",
      manufacturer: "Nichicon",
      description: "A 10μF aluminum electrolytic capacitor rated for 50V. Used for bulk decoupling, power supply filtering, and energy storage in various circuits.",
      datasheetUrl: "https://www.nichicon.co.jp/english/products/pdfs/e-uvr.pdf",
      imageUrl: "/components/cap-10uf.svg",
      footprint: "DIP",
      packageType: "Radial",
      pinCount: 2,
      tags: "capacitor,10uF,electrolytic,filtering,power supply",
      pins: [
        { pinNumber: 1, pinName: "+", description: "Positive terminal (longer lead)" },
        { pinNumber: 2, pinName: "-", description: "Negative terminal (marked stripe)" },
      ],
      specs: [
        { parameter: "Capacitance", value: "10", unit: "μF" },
        { parameter: "Voltage Rating", value: "50", unit: "V" },
        { parameter: "ESR", value: "3.6", unit: "Ω" },
        { parameter: "Ripple Current", value: "32", unit: "mA" },
        { parameter: "Temperature Range", value: "-40 to 85", unit: "°C" },
      ],
    },
    {
      name: "100μF Electrolytic Capacitor",
      category: "Capacitor",
      manufacturer: "Nichicon",
      description: "A 100μF aluminum electrolytic capacitor rated for 25V. Used in power supply filtering, smoothing rectified AC, and bulk energy storage applications.",
      datasheetUrl: "https://www.nichicon.co.jp/english/products/pdfs/e-uvr.pdf",
      imageUrl: "/components/cap-100uf.svg",
      footprint: "DIP",
      packageType: "Radial",
      pinCount: 2,
      tags: "capacitor,100uF,electrolytic,filtering,bulk",
      pins: [
        { pinNumber: 1, pinName: "+", description: "Positive terminal" },
        { pinNumber: 2, pinName: "-", description: "Negative terminal" },
      ],
      specs: [
        { parameter: "Capacitance", value: "100", unit: "μF" },
        { parameter: "Voltage Rating", value: "25", unit: "V" },
        { parameter: "ESR", value: "1.2", unit: "Ω" },
        { parameter: "Temperature Range", value: "-40 to 85", unit: "°C" },
      ],
    },
    {
      name: "1nF Ceramic Capacitor",
      category: "Capacitor",
      manufacturer: "Murata",
      description: "A 1nF multi-layer ceramic capacitor with C0G/NP0 dielectric. Used in high-frequency filtering, timing circuits, and precision analog applications.",
      datasheetUrl: "https://www.murata.com/en-us/products/productdata/8796747038750/ENAB.pdf",
      imageUrl: "/components/cap-1nf.svg",
      footprint: "0603",
      packageType: "0603",
      pinCount: 2,
      tags: "capacitor,1nF,ceramic,precision,high-frequency",
      pins: [
        { pinNumber: 1, pinName: "T1", description: "Terminal 1" },
        { pinNumber: 2, pinName: "T2", description: "Terminal 2" },
      ],
      specs: [
        { parameter: "Capacitance", value: "1", unit: "nF" },
        { parameter: "Voltage Rating", value: "50", unit: "V" },
        { parameter: "Dielectric", value: "C0G/NP0", unit: "" },
        { parameter: "Tolerance", value: "±5", unit: "%" },
      ],
    },
    {
      name: "SRD-05VDC-SL-C",
      category: "Relay",
      manufacturer: "Songle",
      description: "The SRD-05VDC-SL-C is a 5V SPDT (Single Pole Double Throw) electromechanical relay. It can switch loads up to 10A at 250VAC or 10A at 30VDC, making it suitable for home automation and power control.",
      datasheetUrl: "https://www.circuitbasics.com/wp-content/uploads/2015/11/SRD-05VDC-SL-C-Datasheet.pdf",
      imageUrl: "/components/relay-5v.svg",
      footprint: "DIP",
      packageType: "Through-hole Module",
      pinCount: 5,
      tags: "relay,5V,SPDT,switching,power,automation",
      pins: [
        { pinNumber: 1, pinName: "COIL+", description: "Coil positive terminal" },
        { pinNumber: 2, pinName: "COIL-", description: "Coil negative terminal" },
        { pinNumber: 3, pinName: "COM", description: "Common terminal" },
        { pinNumber: 4, pinName: "NO", description: "Normally open contact" },
        { pinNumber: 5, pinName: "NC", description: "Normally closed contact" },
      ],
      specs: [
        { parameter: "Coil Voltage", value: "5", unit: "VDC" },
        { parameter: "Coil Resistance", value: "70", unit: "Ω" },
        { parameter: "Max Switching Voltage", value: "250", unit: "VAC" },
        { parameter: "Max Switching Current", value: "10", unit: "A" },
        { parameter: "Operate Time", value: "10", unit: "ms" },
      ],
    },
    {
      name: "16MHz Crystal Oscillator",
      category: "Crystal Oscillator",
      manufacturer: "Abracon",
      description: "A 16MHz quartz crystal oscillator for generating a stable clock signal. Commonly used with ATmega328P and other microcontrollers requiring an external clock source.",
      datasheetUrl: "https://abracon.com/Resonators/abs07.pdf",
      imageUrl: "/components/crystal-16mhz.svg",
      footprint: "DIP",
      packageType: "HC-49S",
      pinCount: 2,
      tags: "crystal,oscillator,16MHz,clock,quartz",
      pins: [
        { pinNumber: 1, pinName: "X1", description: "Crystal terminal 1" },
        { pinNumber: 2, pinName: "X2", description: "Crystal terminal 2" },
      ],
      specs: [
        { parameter: "Frequency", value: "16", unit: "MHz" },
        { parameter: "Frequency Tolerance", value: "±20", unit: "ppm" },
        { parameter: "Load Capacitance", value: "20", unit: "pF" },
        { parameter: "ESR", value: "40", unit: "Ω" },
      ],
    },
    {
      name: "8MHz Crystal Oscillator",
      category: "Crystal Oscillator",
      manufacturer: "Abracon",
      description: "An 8MHz quartz crystal oscillator for generating clock signals. Used with STM32 and other microcontrollers as the HSE (High Speed External) clock source.",
      datasheetUrl: "https://abracon.com/Resonators/abs07.pdf",
      imageUrl: "/components/crystal-8mhz.svg",
      footprint: "DIP",
      packageType: "HC-49S",
      pinCount: 2,
      tags: "crystal,oscillator,8MHz,clock,quartz,STM32",
      pins: [
        { pinNumber: 1, pinName: "X1", description: "Crystal terminal 1" },
        { pinNumber: 2, pinName: "X2", description: "Crystal terminal 2" },
      ],
      specs: [
        { parameter: "Frequency", value: "8", unit: "MHz" },
        { parameter: "Frequency Tolerance", value: "±20", unit: "ppm" },
        { parameter: "Load Capacitance", value: "18", unit: "pF" },
        { parameter: "ESR", value: "50", unit: "Ω" },
      ],
    },
    {
      name: "Arduino Nano Header",
      category: "Connector",
      manufacturer: "Generic",
      description: "A 2x15 pin female header connector designed for Arduino Nano boards. Provides easy plug-in connection for all Arduino Nano pins on a breadboard or PCB.",
      datasheetUrl: "",
      imageUrl: "/components/nano-header.svg",
      footprint: "DIP",
      packageType: "Through-hole Header",
      pinCount: 30,
      tags: "connector,header,Arduino,Nano,female,pin header",
      pins: [
        { pinNumber: 1, pinName: "D13", description: "Digital pin 13 / SCK / LED" },
        { pinNumber: 2, pinName: "3V3", description: "3.3V output" },
        { pinNumber: 3, pinName: "REF", description: "Analog reference" },
      ],
      specs: [
        { parameter: "Pin Count", value: "30", unit: "pins" },
        { parameter: "Pin Pitch", value: "2.54", unit: "mm" },
        { parameter: "Current Rating", value: "3", unit: "A" },
        { parameter: "Contact Resistance", value: "20", unit: "mΩ" },
      ],
    },
    {
      name: "USB Type-C Connector",
      category: "Connector",
      manufacturer: "Molex",
      description: "A USB Type-C female SMD connector for PCB mounting. Supports USB 2.0 data transfer and 5V power delivery. Commonly used in modern electronics for power input and data connectivity.",
      datasheetUrl: "https://www.molex.com/content/dam/molex/molex-dot-com/products/automated/en-us/salesdrawingpdf/105/1054500101_sd.pdf",
      imageUrl: "/components/usb-c.svg",
      footprint: "SOIC",
      packageType: "SMD",
      pinCount: 16,
      tags: "USB-C,connector,power,data,SMD,Type-C",
      pins: [
        { pinNumber: 1, pinName: "GND", description: "Ground" },
        { pinNumber: 2, pinName: "VBUS", description: "USB power (+5V)" },
        { pinNumber: 3, pinName: "D-", description: "USB data minus" },
        { pinNumber: 4, pinName: "D+", description: "USB data plus" },
      ],
      specs: [
        { parameter: "USB Standard", value: "USB 2.0", unit: "" },
        { parameter: "Voltage Rating", value: "5", unit: "V" },
        { parameter: "Current Rating", value: "3", unit: "A" },
        { parameter: "Data Rate", value: "480", unit: "Mbps" },
      ],
    },
    {
      name: "10kΩ Potentiometer",
      category: "Resistor",
      manufacturer: "Bourns",
      description: "A 10kΩ single-turn linear taper potentiometer. Used for variable voltage division, volume control, brightness adjustment, and other user-adjustable circuit parameters.",
      datasheetUrl: "https://www.bourns.com/docs/Product-Datasheets/3386.pdf",
      imageUrl: "/components/potentiometer.svg",
      footprint: "DIP",
      packageType: "Through-hole",
      pinCount: 3,
      tags: "potentiometer,variable resistor,10k,adjustment,knob",
      pins: [
        { pinNumber: 1, pinName: "T1", description: "Terminal 1 (end)" },
        { pinNumber: 2, pinName: "W", description: "Wiper (adjustable center tap)" },
        { pinNumber: 3, pinName: "T2", description: "Terminal 2 (end)" },
      ],
      specs: [
        { parameter: "Resistance", value: "10", unit: "kΩ" },
        { parameter: "Tolerance", value: "±20", unit: "%" },
        { parameter: "Power Rating", value: "0.5", unit: "W" },
        { parameter: "Taper", value: "Linear (B)", unit: "" },
        { parameter: "Rotational Life", value: "15000", unit: "cycles" },
      ],
    },
    {
      name: "LM2596",
      category: "IC",
      manufacturer: "Texas Instruments",
      description: "The LM2596 is a step-down (buck) switching voltage regulator capable of driving a 3A load with excellent line and load regulation. It operates at 150kHz switching frequency.",
      datasheetUrl: "https://www.ti.com/lit/ds/symlink/lm2596.pdf",
      imageUrl: "/components/lm2596.svg",
      footprint: "DIP",
      packageType: "TO-263",
      pinCount: 5,
      tags: "buck converter,switching regulator,step-down,power,DC-DC",
      pins: [
        { pinNumber: 1, pinName: "VIN", description: "Input voltage" },
        { pinNumber: 2, pinName: "VOUT", description: "Output voltage" },
        { pinNumber: 3, pinName: "GND", description: "Ground" },
        { pinNumber: 4, pinName: "FB", description: "Feedback input" },
        { pinNumber: 5, pinName: "ON/OFF", description: "Enable pin" },
      ],
      specs: [
        { parameter: "Input Voltage Range", value: "4.5 - 40", unit: "V" },
        { parameter: "Output Current", value: "3", unit: "A" },
        { parameter: "Switching Frequency", value: "150", unit: "kHz" },
        { parameter: "Efficiency", value: "92", unit: "%" },
      ],
    },
    {
      name: "PCF8574",
      category: "IC",
      manufacturer: "NXP Semiconductors",
      description: "The PCF8574 is a remote 8-bit I/O expander for the I2C bus. It provides general-purpose remote I/O expansion and is commonly used to add GPIO pins to microcontrollers via I2C.",
      datasheetUrl: "https://www.nxp.com/docs/en/data-sheet/PCF8574_PCF8574A.pdf",
      imageUrl: "/components/pcf8574.svg",
      footprint: "DIP",
      packageType: "DIP-16",
      pinCount: 16,
      tags: "I2C,IO expander,GPIO,bus,port expander",
      pins: [
        { pinNumber: 1, pinName: "A0", description: "Address bit 0" },
        { pinNumber: 2, pinName: "A1", description: "Address bit 1" },
        { pinNumber: 3, pinName: "A2", description: "Address bit 2" },
        { pinNumber: 4, pinName: "P0", description: "GPIO port bit 0" },
        { pinNumber: 5, pinName: "P1", description: "GPIO port bit 1" },
        { pinNumber: 6, pinName: "P2", description: "GPIO port bit 2" },
        { pinNumber: 7, pinName: "P3", description: "GPIO port bit 3" },
        { pinNumber: 8, pinName: "GND", description: "Ground" },
        { pinNumber: 9, pinName: "P4", description: "GPIO port bit 4" },
        { pinNumber: 10, pinName: "P5", description: "GPIO port bit 5" },
        { pinNumber: 11, pinName: "P6", description: "GPIO port bit 6" },
        { pinNumber: 12, pinName: "P7", description: "GPIO port bit 7" },
        { pinNumber: 13, pinName: "INT", description: "Interrupt output (active low)" },
        { pinNumber: 14, pinName: "SCL", description: "I2C clock" },
        { pinNumber: 15, pinName: "SDA", description: "I2C data" },
        { pinNumber: 16, pinName: "VCC", description: "Supply voltage" },
      ],
      specs: [
        { parameter: "Supply Voltage", value: "2.5 - 6", unit: "V" },
        { parameter: "I2C Speed", value: "100", unit: "kHz" },
        { parameter: "I/O Ports", value: "8", unit: "" },
        { parameter: "Sink Current", value: "25", unit: "mA" },
      ],
    },
    {
      name: "MCP23017",
      category: "IC",
      manufacturer: "Microchip",
      description: "The MCP23017 is a 16-bit I/O expander with I2C interface. It provides 16 GPIO pins organized in two 8-bit ports, with individual pin direction and polarity control.",
      datasheetUrl: "https://ww1.microchip.com/downloads/en/devicedoc/20001952c.pdf",
      imageUrl: "/components/mcp23017.svg",
      footprint: "DIP",
      packageType: "DIP-28",
      pinCount: 28,
      tags: "I2C,IO expander,16-bit,GPIO,port expander",
      pins: [
        { pinNumber: 1, pinName: "GPB0", description: "Port B bit 0" },
        { pinNumber: 2, pinName: "GPB1", description: "Port B bit 1" },
        { pinNumber: 3, pinName: "GPB2", description: "Port B bit 2" },
        { pinNumber: 4, pinName: "GPB3", description: "Port B bit 3" },
      ],
      specs: [
        { parameter: "Supply Voltage", value: "1.8 - 5.5", unit: "V" },
        { parameter: "I2C Speed", value: "100/400/1700", unit: "kHz" },
        { parameter: "I/O Ports", value: "16", unit: "" },
        { parameter: "Output Current", value: "25", unit: "mA" },
      ],
    },
    {
      name: "MAX7219",
      category: "IC",
      manufacturer: "Maxim Integrated",
      description: "The MAX7219 is a serially interfaced, 8-digit LED display driver. It can drive up to 64 individual LEDs or an 8x8 LED matrix using only 3 wires (SPI). Common cathode display interface.",
      datasheetUrl: "https://datasheets.maximintegrated.com/en/ds/MAX7219-MAX7221.pdf",
      imageUrl: "/components/max7219.svg",
      footprint: "DIP",
      packageType: "DIP-24",
      pinCount: 24,
      tags: "LED driver,7-segment,matrix,SPI,display,MAX7219",
      pins: [
        { pinNumber: 1, pinName: "DIN", description: "Serial data input" },
        { pinNumber: 4, pinName: "GND", description: "Ground" },
        { pinNumber: 12, pinName: "LOAD/CS", description: "Chip select (active low)" },
        { pinNumber: 13, pinName: "CLK", description: "Serial clock input" },
        { pinNumber: 19, pinName: "VCC", description: "Supply voltage (+5V)" },
        { pinNumber: 24, pinName: "DOUT", description: "Serial data output (daisy-chain)" },
      ],
      specs: [
        { parameter: "Supply Voltage", value: "4.0 - 5.5", unit: "V" },
        { parameter: "Max Segment Current", value: "40", unit: "mA" },
        { parameter: "Interface", value: "SPI", unit: "" },
        { parameter: "Max SPI Clock", value: "10", unit: "MHz" },
        { parameter: "Digits", value: "8", unit: "" },
      ],
    },
    {
      name: "DS18B20",
      category: "Sensor",
      manufacturer: "Maxim Integrated",
      description: "The DS18B20 is a programmable-resolution 1-Wire digital thermometer with ±0.5°C accuracy from -10°C to +85°C. Each device has a unique 64-bit serial code for multi-sensor networks.",
      datasheetUrl: "https://datasheets.maximintegrated.com/en/ds/DS18B20.pdf",
      imageUrl: "/components/ds18b20.svg",
      footprint: "TO-92",
      packageType: "TO-92",
      pinCount: 3,
      tags: "temperature,sensor,1-Wire,digital,waterproof",
      pins: [
        { pinNumber: 1, pinName: "GND", description: "Ground" },
        { pinNumber: 2, pinName: "DQ", description: "Data I/O (1-Wire bus)" },
        { pinNumber: 3, pinName: "VDD", description: "Power supply (3.0V - 5.5V)" },
      ],
      specs: [
        { parameter: "Operating Voltage", value: "3.0 - 5.5", unit: "V" },
        { parameter: "Temperature Range", value: "-55 to 125", unit: "°C" },
        { parameter: "Accuracy", value: "±0.5", unit: "°C" },
        { parameter: "Resolution", value: "9 - 12", unit: "bit" },
        { parameter: "Conversion Time", value: "750", unit: "ms" },
      ],
    },
    {
      name: "BMP280",
      category: "Sensor",
      manufacturer: "Bosch Sensortec",
      description: "The BMP280 is a barometric pressure and temperature sensor with high accuracy and low power consumption. It supports I2C and SPI interfaces and is ideal for weather stations and altitude measurement.",
      datasheetUrl: "https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmp280-ds001.pdf",
      imageUrl: "/components/bmp280.svg",
      footprint: "QFN",
      packageType: "LGA-8",
      pinCount: 8,
      tags: "pressure,temperature,barometer,altitude,I2C,SPI",
      pins: [
        { pinNumber: 1, pinName: "VDD", description: "Supply voltage (1.8V - 3.6V)" },
        { pinNumber: 2, pinName: "GND", description: "Ground" },
        { pinNumber: 3, pinName: "SCL/SCK", description: "I2C clock / SPI clock" },
        { pinNumber: 4, pinName: "SDA/SDI", description: "I2C data / SPI data in" },
      ],
      specs: [
        { parameter: "Pressure Range", value: "300 - 1100", unit: "hPa" },
        { parameter: "Pressure Accuracy", value: "±1", unit: "hPa" },
        { parameter: "Temperature Range", value: "-40 to 85", unit: "°C" },
        { parameter: "Temperature Accuracy", value: "±1", unit: "°C" },
        { parameter: "Interface", value: "I2C / SPI", unit: "" },
        { parameter: "Operating Voltage", value: "1.8 - 3.6", unit: "V" },
      ],
    },
    {
      name: "MPU6050",
      category: "Sensor",
      manufacturer: "InvenSense",
      description: "The MPU6050 is a 6-axis motion tracking device combining a 3-axis gyroscope and 3-axis accelerometer with a Digital Motion Processor (DMP). Widely used in drones, robots, and motion-sensing applications.",
      datasheetUrl: "https://invensense.tdk.com/wp-content/uploads/2015/02/MPU-6000-Datasheet1.pdf",
      imageUrl: "/components/mpu6050.svg",
      footprint: "QFN",
      packageType: "QFN-24",
      pinCount: 8,
      tags: "accelerometer,gyroscope,IMU,motion,I2C,6-axis",
      pins: [
        { pinNumber: 1, pinName: "VCC", description: "Power supply (3.3V - 5V)" },
        { pinNumber: 2, pinName: "GND", description: "Ground" },
        { pinNumber: 3, pinName: "SCL", description: "I2C clock" },
        { pinNumber: 4, pinName: "SDA", description: "I2C data" },
        { pinNumber: 5, pinName: "XDA", description: "Auxiliary I2C data" },
        { pinNumber: 6, pinName: "XCL", description: "Auxiliary I2C clock" },
        { pinNumber: 7, pinName: "AD0", description: "I2C address select" },
        { pinNumber: 8, pinName: "INT", description: "Interrupt output" },
      ],
      specs: [
        { parameter: "Gyroscope Range", value: "±250 to ±2000", unit: "°/s" },
        { parameter: "Accelerometer Range", value: "±2 to ±16", unit: "g" },
        { parameter: "ADC Resolution", value: "16", unit: "bit" },
        { parameter: "Operating Voltage", value: "2.375 - 3.46", unit: "V" },
        { parameter: "I2C Address", value: "0x68 / 0x69", unit: "" },
      ],
    },
    {
      name: "ESP8266 (ESP-01)",
      category: "Microcontroller",
      manufacturer: "Espressif",
      description: "The ESP-01 is the smallest ESP8266 Wi-Fi module, featuring a 32-bit Tensilica L106 processor, 1MB flash, and full Wi-Fi stack. It can function as a standalone microcontroller or Wi-Fi adapter.",
      datasheetUrl: "https://www.espressif.com/sites/default/files/documentation/0a-esp8266ex_datasheet_en.pdf",
      imageUrl: "/components/esp01.svg",
      footprint: "DIP",
      packageType: "Module",
      pinCount: 8,
      tags: "WiFi,IoT,ESP8266,wireless,module,web server",
      pins: [
        { pinNumber: 1, pinName: "GND", description: "Ground" },
        { pinNumber: 2, pinName: "GPIO2", description: "General purpose I/O 2" },
        { pinNumber: 3, pinName: "GPIO0", description: "General purpose I/O 0 / Boot mode" },
        { pinNumber: 4, pinName: "RXD", description: "UART receive" },
        { pinNumber: 5, pinName: "TXD", description: "UART transmit" },
        { pinNumber: 6, pinName: "CH_PD", description: "Chip enable (active high)" },
        { pinNumber: 7, pinName: "RST", description: "Reset (active low)" },
        { pinNumber: 8, pinName: "VCC", description: "Power supply (3.3V)" },
      ],
      specs: [
        { parameter: "CPU", value: "Tensilica L106 32-bit", unit: "" },
        { parameter: "Clock Speed", value: "80/160", unit: "MHz" },
        { parameter: "Flash Memory", value: "1", unit: "MB" },
        { parameter: "Wi-Fi", value: "802.11 b/g/n", unit: "" },
        { parameter: "Operating Voltage", value: "3.0 - 3.6", unit: "V" },
        { parameter: "GPIO Pins", value: "2", unit: "" },
      ],
    },
    {
      name: "Zener Diode 5.1V",
      category: "Diode",
      manufacturer: "ON Semiconductor",
      description: "A 5.1V Zener diode used for voltage regulation and protection. In reverse breakdown, it maintains a stable 5.1V across its terminals, making it useful for voltage clamping and reference circuits.",
      datasheetUrl: "https://www.onsemi.com/pdf/datasheet/1n5221b-d.pdf",
      imageUrl: "/components/zener-5v1.svg",
      footprint: "DIP",
      packageType: "DO-35",
      pinCount: 2,
      tags: "Zener,diode,5.1V,voltage regulation,protection,clamping",
      pins: [
        { pinNumber: 1, pinName: "A", description: "Anode" },
        { pinNumber: 2, pinName: "K", description: "Cathode (band marking)" },
      ],
      specs: [
        { parameter: "Zener Voltage", value: "5.1", unit: "V" },
        { parameter: "Power Dissipation", value: "500", unit: "mW" },
        { parameter: "Zener Current", value: "20", unit: "mA" },
        { parameter: "Tolerance", value: "±5", unit: "%" },
      ],
    },
    {
      name: "ULN2003A",
      category: "IC",
      manufacturer: "Texas Instruments",
      description: "The ULN2003A is a high-voltage, high-current Darlington transistor array. It contains seven NPN Darlington pairs with common-cathode clamp diodes for switching inductive loads like stepper motors, relays, and solenoids.",
      datasheetUrl: "https://www.ti.com/lit/ds/symlink/uln2003a.pdf",
      imageUrl: "/components/uln2003a.svg",
      footprint: "DIP",
      packageType: "DIP-16",
      pinCount: 16,
      tags: "Darlington array,driver,stepper motor,relay driver,high current",
      pins: [
        { pinNumber: 1, pinName: "1B", description: "Input 1" },
        { pinNumber: 2, pinName: "2B", description: "Input 2" },
        { pinNumber: 3, pinName: "3B", description: "Input 3" },
        { pinNumber: 4, pinName: "4B", description: "Input 4" },
        { pinNumber: 5, pinName: "5B", description: "Input 5" },
        { pinNumber: 6, pinName: "6B", description: "Input 6" },
        { pinNumber: 7, pinName: "7B", description: "Input 7" },
        { pinNumber: 8, pinName: "GND", description: "Ground" },
        { pinNumber: 9, pinName: "COM", description: "Common free-wheeling diode" },
        { pinNumber: 10, pinName: "7C", description: "Output 7" },
        { pinNumber: 11, pinName: "6C", description: "Output 6" },
        { pinNumber: 12, pinName: "5C", description: "Output 5" },
        { pinNumber: 13, pinName: "4C", description: "Output 4" },
        { pinNumber: 14, pinName: "3C", description: "Output 3" },
        { pinNumber: 15, pinName: "2C", description: "Output 2" },
        { pinNumber: 16, pinName: "1C", description: "Output 1" },
      ],
      specs: [
        { parameter: "Output Voltage", value: "50", unit: "V" },
        { parameter: "Output Current", value: "500", unit: "mA" },
        { parameter: "Input Voltage", value: "5", unit: "V" },
        { parameter: "Number of Channels", value: "7", unit: "" },
      ],
    },
  ];

  let createdCount = 0;

  for (const comp of components) {
    const created = await prisma.component.create({
      data: {
        name: comp.name,
        category: comp.category,
        manufacturer: comp.manufacturer,
        description: comp.description,
        datasheetUrl: comp.datasheetUrl || null,
        imageUrl: comp.imageUrl || null,
        footprint: comp.footprint || null,
        packageType: comp.packageType || null,
        pinCount: comp.pinCount || null,
        tags: comp.tags || "",
        pins: {
          create: comp.pins.map((p) => ({
            pinNumber: p.pinNumber,
            pinName: p.pinName,
            description: p.description,
          })),
        },
        specifications: {
          create: comp.specs.map((s) => ({
            parameter: s.parameter,
            value: s.value,
            unit: s.unit || null,
          })),
        },
      },
    });
    createdCount++;
    console.log(`  📦 Created: ${created.name}`);
  }

  console.log(`\n✅ Seeded ${createdCount} components`);
  console.log("🎉 Database seeding complete!");
}

main()
  .catch((e) => {
    console.error("❌ Seed error:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
